jkp_admin:
    resource: "@JKPAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

jkp_core:
    resource: "@JKPCoreBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
          _locale: pl|en|hu

core_nolocale:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: jkp_core_homepage
        permanent: true # this is for 301
