security:
    providers:
        in_memory:
            memory:
                users:
                    agatadmin: { password: pass, roles: 'ROLE_ADMIN' }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$
            security: false

        secured_area:
            pattern:   ^/admin
            provider: in_memory
            form_login:
                login_path: jkp_admin_login
                check_path: jkp_admin_login_check
            logout:
                path:   jkp_admin_logout
                target: /admin
        default:
            anonymous: ~

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }